spring:
  application:
    name: HOTEL-SERVICE-FROM-CONFIG

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka
      
  instance:
    prefer-ip-address: true

test:
  name: something ra pooka


